### ISSUE TITLE
vercel app down and self host error

### ISSUE THREAD

**Issue by ValgulNecron** [KangieDanie/AniCalendar#4]
hi, i wanted to test the app but your vecel gave me this error 
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: cdg1::gb9lm-1677937175920-c47db70809d1

i then tried to deploy it myself on vercel with the env set but i got this error 
{"error":"invalid_client","message":"Client authentication failed"}
but when i pasted the url that i got from anilist
https://anilist.co/api/v2/oauth/authorize?client_id=[ap_id]&scope=&response_type=code&redirect_uri=https%3A%2F%2Fani-calendar-cma4-59bj5beul-valgulnecron.vercel.app%2Fapi%2Fauth%2Fcallback%2FAniListProvider&state=[something_like_a_token]
postman return me no error but the replied any idea how i can fix it ?

**Comment by ValgulNecron** [comment]
for the second error i found how to patch it 
if you are not on vercel you will need 
NEXTAUTH_URL=[URL]
and NEXTAUTH_SECRET=[SECRET]
also you need to make so your client redirect to the callback url so something like this [url]/api/auth/callback/AniListProvider

**Comment by KangieDanie** [comment]
Hey Sorry for the late reply. 

NEXTAUTH_SECRET is required when launching in production. 

When you are creating a new App on Anilist, you'll have to set Redirect URL like in the image below.
![image](https://user-images.githubusercontent.com/95631180/222980170-96d86a92-15c7-470b-ae9a-8396418f3c20.png)

I'll add this information to the readme.
Thanks!
