### ISSUE TITLE
Unable to generate image

### ISSUE THREAD

**Issue by realFPS** [KangieDanie/AniCalendar#8]
It keeps on buffering. I tried on Edge, firefox browser and Firefox mobile. The results were identical.
![image](https://user-images.githubusercontent.com/77321589/230709134-ad5b708c-0cd4-4541-851d-1dbba6187378.png)

**Comment by KangieDanie** [comment]
Thanks, I will look for a solution

**Comment by DarkHole1** [comment]
I debugged problem by myself and found that `html-to-image` requires same origin. `no-cors` breaks everything. Same for `html2canvas` and I guess there is no way to fix it without bypassing cors.

I don't familiar with Next.js, but maybe there is possible solution with rewrites. Something like:
```js
module.exports = {
  async rewrites() {
    return [
      {
        source: '/cors/:path*',
        destination: 'https://s4.anilist.co/:path*' // Proxy to Backend
      }
    ]
  }
}
```
And then replacing `s4.anilist.co` with `/cors`.

**Comment by ChurroC** [comment]
You could do
```
 const downloadImage = async (): Promise<void> => {
    setLoadingVisible(true);
    if (refElement) {
      try {
        const dataUrl = await toPng(refElement.current, { cacheBust: true });
        const link = document.createElement('a');
        link.download = `calendar-${year}-${month}.png`;
        link.href = dataUrl;
        link.click();
        link.click();
      } catch (error) {
        console.log(error);
      }
      setLoadingVisible(false);
    }
  }
```
which is in my pull request

**Comment by KangieDanie** [comment]
This is issue has been solved by @ChurroC.
